apiVersion: v1
kind: Service

metadata:
  name: redis-sentinel-headless

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: hangeul-chat-redis-sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
