apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_DATABASE: hangeul_chat
  MYSQL_USER: hangeul_user
  MYSQL_PASSWORD: "1234"
  MARIADB_REPLICATION_USER: repl_user
  MARIADB_REPLICATION_PASSWORD: "1234"

