apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "1234"
  MARIADB_DATABASE: hangeul_chat
  MARIADB_USER: hangeul_user
  MARIADB_PASSWORD: "1234"
  MARIADB_REPLICATION_USER: repl_user
  MARIADB_REPLICATION_PASSWORD: "1234"

